### ISSUE TITLE
Inclusão de {{cpf}}

### ISSUE THREAD

**Issue by hilsongva** [ifpeopensource/certificate-generator#1]
Parabéns pelo Projeto, que está contribuindo para agilizarmos a emissão de certificados na Extensão do IFPE-Campus Recife! Uma feature que seria muito útil, para evitarmos confusões de certificados de homônimos, seria a inclusão do {{cpf}} além do {{nome}}

**Comment by weltonfelix** [comment]
Muito obrigado! Foi feito um commit (11492c619d504471d3f324b50166e9b925fbae7a) adicionando a feature de múltiplos campos. Além do CPF, podem ser adicionados outros dados como o título da atividade para qual o certificado está sendo gerado, data etc. Para isso é necessário realizar a entrada de dados por meio de um arquivo csv (como no [exemplo](https://github.com/ifpeopensource/certificate-generator/blob/11492c619d504471d3f324b50166e9b925fbae7a/data.example.csv)).

Assim, para incluir o CPF poderia ser adicionado no texto do slide um campo `{{cpf}}` e um campo cpf no csv (que pode ser gerado utilizando ferramentas como o Excel ou LibreOffice Calc.

Ex.:
```
name,cpf
Pessoa A,123.456.789-10
Pessoa B, 109.876.543-21
```

Também foi mantida a funcionalidade de adicionar apenas nomes, para facilitar a geração em certos casos mais simples.

A mudança é que para executar o programa é preciso informar o arquivo contendo os dados e o programa irá perguntar se o certificado será preenchido com múltiplos campos (caso o arquivo seja csv) ou apenas com os nomes (caso o arquivo seja txt). Essa informação também pode ser passada previamente para evitar que o programa pergunte:
Ex.:
Para preencher apenas os nomes:
```bash
python main.py -d names.txt --name-only
```

Para preencher múltiplos campos a partir de um csv:
```bash
python main.py -d data.csv --multiple-fields
```
